# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Tanya umum / diskusi
    url: https://github.com/erwansistandi/erwan-devops-templates/discussions
    about: Gunakan Discussions untuk tanya jawab umum
