name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CI Sanity Check
        run: |
          echo "CI berjalan 👍"
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
